# Generated by Django 6.0 on 2026-02-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oldcart',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
