# Generated by Django 6.0 on 2026-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
